services:
  label-system:
    build: .
    container_name: label-system
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
